// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvidenceBotDAL;

namespace ProvidenceBotDAL.Migrations.Migrations
{
  [DbContext(typeof(SuggestContext))]
  [Migration("20210514171140_InitialCreate")]
  partial class InitialCreate
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
      #pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("Relational:MaxIdentifierLength", 128)
        .HasAnnotation("ProductVersion", "5.0.6")
        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("ProvidenceBotDAL.Models.items.Item", b =>
      {
        b.Property<int>("ID")
          .ValueGeneratedOnAdd()
          .HasColumnType("int")
          .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        b.Property<string>("Description")
          .HasColumnType("nvarchar(max)");

        b.Property<string>("Name")
          .HasColumnType("nvarchar(max)");

        b.HasKey("ID");

        b.ToTable("Items");
      });
      #pragma warning restore 612, 618
    }
  }
}
